# Generated by Django 4.1.5 on 2023-02-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percent_discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
