# Generated by Django 4.1.5 on 2023-02-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount_percent_discount'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersItem',
            new_name='OrderItems',
        ),
    ]
