# Generated by Django 4.1.5 on 2023-02-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Posted', 'posted'), ('Packing', 'packing')], default='packing', max_length=10),
        ),
    ]
